### ISSUE TITLE
Emacs crashes with 4 sites

### ISSUE THREAD

**Issue by tomykaira** [hchbaw/anything-c-javadoc.el#2]
試しに次の4つのサイトを登録し、`M-x anything-c-javadoc`を実行してキャッシュの構築を始めたところ、
処理途中で(おそらくメモリを食いつくして) emacs を巻き込んでクラッシュしました。

```
'("http://java.sun.com/javase/6/docs/api/"
  "http://kentbeck.github.com/junit/javadoc/latest/"
  "http://msgpack.org/javadoc/current/"
  "http://docs.mockito.googlecode.com/hg/latest/org/mockito/")
```

**Comment by hchbaw** [comment]
ごめんなさい、今の実装ってリソース使いまくりすぎですよね…

テキストプロパティを使わないようにして、eijiro.elのようにgrep使うような感じにもできるようにしようかしらん…等と思ってはいます…

今のところ思っているだけです、ごめんなさいごめんなさい。
